import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useAppDispatch } from '../hooks/redux';
import Link from 'next/link';

const Home: NextPage = () => {
  const dispatch = useAppDispatch();

  const onClick = () => {
    console.log('btn click');
    dispatch({type: 'TEST'})
  };

  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/Users/oksen/OneDrive/Desktop/next-js-starter/public/favicon.ico"/>
      </Head>

      <main >
        <h1 >
          <Link href='/'>go go go main</Link>
          <button onClick={ onClick }>CLICK TEST</button>
        </h1>


      </main>
    </div>
  );
};

export default Home;
